### ISSUE TITLE
Merging upstream?

### ISSUE THREAD

**Issue by stephenplusplus** [JustinBeckwith/duplexify#3]
Do you plan to get this into the upstream repo?

**Comment by JustinBeckwith** [comment]
Right now this is still in the experimental stage.  I kind of want to make 100% we don't need the user space `ReadableStream` package, and see where things go from there.  If the original author is cool with the changes I've made (which have been many...) I am 100% for contributing upstream.

**Comment by JustinBeckwith** [comment]
Just to keep this going - I submitted a few issues upstream to feel it out:
- https://github.com/mafintosh/duplexify/issues/23
- https://github.com/mafintosh/duplexify/issues/24

**Comment by JustinBeckwith** [comment]
Looks like there wasn't a lot of interest 🤷‍♂️
